# Generated by Django 4.2.3 on 2023-07-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_wine'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wine',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
