# Generated by Django 4.2.3 on 2023-07-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_outofstockitem_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='outofstockitem',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outofstockitem',
            name='username',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
